export type { Complex, NewsItem, TeamMember, VideoItem } from './types'
export type {
	StrapiAbout,
	StrapiAboutAttributes,
	StrapiEmployee,
	StrapiEmployeeAttributes,
	StrapiEntity,
	StrapiMainSlider,
	StrapiMainSliderAttributes,
	StrapiMedia,
	StrapiMediaArray,
	StrapiNews,
	StrapiNewsAttributes,
	StrapiNumber,
	StrapiNumberAttributes,
	StrapiResidentialComplex,
	StrapiResidentialComplexAttributes,
	StrapiResponse,
	StrapiSingleResponse,
	StrapiSlide,
	StrapiSlideAttributes,
	StrapiSocialNetwork,
	StrapiSocialNetworkAttributes,
	StrapiVideoBlog,
	StrapiVideoBlogAttributes,
} from './strapi'
