export const TEXTS = {
  about_us: "О нас",
  address: "Адрес",
  bonus_per_sqm: "за м²",
  catalog: "Каталог",
  close: "Закрыть",
  contact_form_full_name_placeholder: "Имя и фамилия",
  contact_form_or_call: "Или позвоните нам ",
  contact_form_phone_placeholder: "Номер телефона",
  contact_form_privacy_link: "Политики конфиденциальности",
  contact_form_privacy_text: "Нажимая на кнопку вы соглашаетесь с условиями",
  contact_form_submit: "Оставить заявку",
  contact_form_title: "Оставьте заявку",
  contact_phone: "+7 (989) 872 89 99",
  earn_with_friends: "Зарабатывайте вместе с друзьями",
  etalon_invest: "Эталон Инвест",
  golden_card: "Золотая карта",
  home: "Главная",
  housing_complexes: "Жилищные комплексы",
  inviting_realtors: "Приглашаем риелторов",
  max_bonus: "максимальный бонус",
  news: "Новости",
  our_people: "Наша команда",
  phone: "Телефон",
  referral_system: "Реферальная система",
  up_to_1000_per_sqm: "до 1000 Р",
  video: "Видео",
  videoblog: "Видеоблог",
} as const;
