export const TEXTS = {
  about_us: 'О нас',
  address: 'Адрес',
  bonus_per_sqm: 'за м²',
  catalog: 'Каталог',
  earn_with_friends: 'Зарабатывайте вместе с друзьями',
  etalon_invest: 'Эталон Инвест',
  golden_card: 'Золотая карта',
  home: 'Главная',
  housing_complexes: 'Жилые комплексы',
  inviting_realtors: 'Приглашаем риелторов',
  max_bonus: 'максимальный бонус',
  news: 'Новости',
  our_people: 'Наша команда',
  phone: 'Телефон',
  referral_system: 'Реферальная система',
  up_to_1000_per_sqm: 'до 1000 Р',
  videoblog: 'Видеоблог',
} as const;
